### ISSUE TITLE
Please attach Xcode 11 Carthage build to latest release

### ISSUE THREAD

**Issue by jonreid** [uber/ios-snapshot-test-case#103]
Thanks!

**Comment by peacemoon** [comment]
@reidmain  can you create a new tag/release.

**Comment by jonreid** [comment]
A new tag/release isn't necessary. Just a new attachment to the release.

**Comment by reidmain** [comment]
[v6.2.0](https://github.com/uber/ios-snapshot-test-case/releases/tag/6.2.0) has been released and it was built with Xcode 11.1 and Swift 5.1
