### ISSUE TITLE
UIImage not capture while taking reference images

### ISSUE THREAD

**Issue by vineetkhoticonvo** [uber/ios-snapshot-test-case#115]
Hi, 
I am using Xcode 11.2.1. I had UIImage object on my view like logo image, but while capturing reference image with recordMode = true, logo image of view controller not display on reference image for that view. Do we need to setup any property or change any parameter in build setting ?

This is simulator screenshot - 
![Simulator Screen Shot - iPhone 8 - 2019-11-25 at 21 13 14](https://user-images.githubusercontent.com/57626188/69555138-b606db80-0fc8-11ea-8c8d-01157edf9feb.png)

This is reference folder image - 

![image](https://user-images.githubusercontent.com/57626188/69555253-e3538980-0fc8-11ea-8d1d-dc227ef56341.png)

**Comment by Kurt57** [comment]
Can you please paste your code ?

May you have to wait that your view is created?

**Comment by kmuralidharan91** [comment]
hi @vineetkhoticonvo did you got the above issue fixed?

i am also facing the same problem. can you guide me on this?

**Comment by vineetkhoticonvo** [comment]
> hi @vineetkhoticonvo did you got the above issue fixed?
> 
> i am also facing the same problem. can you guide me on this?

I was using UI Testing bundle, hence getting failed. Please use Unit Testing Bundle and then check..it will work.
