### ISSUE TITLE
[Carthage] "iOS-snapshot-test-case" fails to build on 12.0 beta 5

### ISSUE THREAD

**Issue by pBoelck** [uber/ios-snapshot-test-case#133]
The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.1, but the range of supported deployment target versions is 9.0 to 14.0.99. (in target 'FBSnapshotTestCase iOS Tests' from project 'FBSnapshotTestCase')

**Comment by bielikb** [comment]
Im having the same issue, running Xcode 12.0 beta 6

**Comment by alanzeino** [comment]
should be resolved but try switching to swiftpm integration if you can, carthage support may go away at some point
