### ISSUE TITLE
 Is this library already deprecated?

### ISSUE THREAD

**Issue by mzapatae** [uber/ios-snapshot-test-case#136]
Since apparently this library is already deprecated since there is no development (nor any type of support since the issues are going up and none without response), is there any other snapshot lib or fork that is more maintained?

**Comment by liuxuan30** [comment]
I think you can grab the source code to fix for Xcode12 at least for now.
I'm facing the same issue too... wonder who can fix Xcode12.

**Comment by alanzeino** [comment]
Read here https://github.com/uber/ios-snapshot-test-case/pull/126#issuecomment-723352614

**Comment by kikeenrique** [comment]
Read here too, @alanzeino fork with SPM integrated https://github.com/uber/ios-snapshot-test-case/pull/126#issuecomment-801631166
