### ISSUE TITLE
Latest version not available through CocoaPods

### ISSUE THREAD

**Issue by djpearce** [uber/ios-snapshot-test-case#157]
You local Podspec file needs pushed to trunk since your 7.0.0 release.

Here is the currently available spec file from CocoaPods:

https://github.com/CocoaPods/Specs/blob/master/Specs/8/8/a/iOSSnapshotTestCase/6.2.0/iOSSnapshotTestCase.podspec.json

Just need to run:

`pod trunk push iOSSnapshotTestCase.podspec`

**Comment by alanzeino** [comment]
yeah still working on this, cocoapods hasn't given me write access
