### ISSUE TITLE
Take multiple snapshots to the same view

### ISSUE THREAD

**Issue by ahmdyasser** [uber/ios-snapshot-test-case#181]
Is it possible to take a snapshot to `view1` then move to `view2` then go back to `view1` to check if any changes happened during that moving between the two views?

**Comment by alanzeino** [comment]
What does 'moving' mean in this context? Is this an animation between two views? Or are these two static views but you're seeing a bug where the first one changes layout after a side effect from the second one?

**Comment by ahmdyasser** [comment]
@alanzeino  Honestly I don't remember what what the scenario, but I guess I've done that task so am closing this issue.
