### ISSUE TITLE
UIKeyboardDidShowNotification not fired in snapshot tests running on iOS11 device

### ISSUE THREAD

**Issue by cckring** [uber/ios-snapshot-test-case#20]
I have a few snapshot tests which test that the view is correctly setup when the keyboard is shown. 

However, on iOS11 devices the UIKeyboardDidShowNotification is never fired during the snapshot tests and evidently the keyboard is never shown.

Has anyone out there faced this and come op with a solution?

I believe this is not actually an issue with ios-snapshot-test-case, but now I put it here because you may have the insights to help me.

**Comment by cckring** [comment]
I decided to also post a question to StackOverflow:
https://stackoverflow.com/questions/49032799/uikeyboarddidshownotification-not-fired-in-ios-snapshot-test-case-tests-running

**Comment by alanzeino** [comment]
When you reset the simulator, does the keyboard appear as expected?

Are you attempting to present the simulator as the result of making a text input field (like a UITextField or a UITextView) the first responder? To be honest, I don't think the keyboard can ever be seen in a snapshot. I believe it is out of process and not visible to your application specifically.

**Comment by cckring** [comment]
Yes - the keyboard is shown because an input field is first responder.

I have a keyboard observer setup, so when my tests are running on iOS10 and below I kan go through the windows to find the keyboard and then I have made a small hack in my test that adds the keyboard to the view of my sut before taking the snapshot.

However, when running on iOS11 the keyboard notififation is never fired when in my snapshot tests.

`- (void)didShowKeyboard:(NSNotification *)notification {
    NSLog(@"%s", sel_getName(_cmd));

    UIWindow *myWindow;
    for(UIWindow* window in [[UIApplication sharedApplication] windows]) {
        if([window isKindOfClass:NSClassFromString(@"UIRemoteKeyboardWindow")]) {
            myWindow = window;
        }
    }

    [sut.view addSubview:myWindow];
    FBSnapshotVerifyView(sut.view, nil);

}`

**Comment by alanzeino** [comment]
Well, that seems like a bug in iOS 11. Sorry!
