### ISSUE TITLE
not an issue - swift repo - fyi

### ISSUE THREAD

**Issue by wwe-johndpope** [uber/ios-snapshot-test-case#21]
https://github.com/AndriiDoroshko/SnappyShrimp

**Comment by alanzeino** [comment]
and https://github.com/pointfreeco/swift-snapshot-testing and https://github.com/skyweb07/Snap.swift

**Comment by freak4pc** [comment]
FYI to whoever finds this - the main issue with _any_ swift-based solutions is that they are extremely slow for comparing on a pixel-to-pixel basis due to Swift's safety mechanisms.
