### ISSUE TITLE
Opportunity to update license information?

### ISSUE THREAD

**Issue by spectejb** [uber/ios-snapshot-test-case#22]
Would it be possible to relicense the entire project - including the Facebook code that now appears to be owned/managed by Uber - under a MIT license?  The Facebook BSD+Patent license prevents us from using the software in my company and it appears that the transfer of ownership may allow this license change.  Thanks for your consideration!

**Comment by spectejb** [comment]
@alanzeino* and team - I know how busy work can get so just checking in on this request.  Looking forward to hearing from you!

*I saw you were helping with other issues for this project.

**Comment by alanzeino** [comment]
@briankhsieh can we answer this one? I think there were some specific reasons why we picked this approach.

**Comment by briankhsieh** [comment]
Let me consult the legal team. I will get back to you.

**Comment by briankhsieh** [comment]
Hi, we are exploring the possibility of relicensing the project. I will update here once there's a definitive answer.

**Comment by alanzeino** [comment]
Facebook relicensed the original archived project today, so we have published a new version (`3.0.0`) with the entire project relicensed under MIT, without the PATENTS file.

Thank you to Facebook (@zpao and others) for working with us closely to get such a speedy resolution and to Brian and Matt at Uber as well!

**Comment by spectejb** [comment]
I echo your thank yous, @alanzeino.  Really appreciate the time spent on this by the Uber and Facebook teams!
