### ISSUE TITLE
MaskedCorners in CALayer are not displayed correctly

### ISSUE THREAD

**Issue by m-ruhl** [uber/ios-snapshot-test-case#25]
We created a view with `maskedCorners` defined.

```swift
$0.layer.cornerRadius = layer.cornerRadius
$0.layer.maskedCorners = [.layerMaxXMaxYCorner, .layerMinXMaxYCorner]
```

Unfortunately there are not correctly rendered in the snapshot test:
<img width="500" alt="testviewcontrollernormal 2x" src="https://user-images.githubusercontent.com/867772/37719883-64d49972-2d26-11e8-9e04-99d292197c56.png">
<img width="500" alt="testviewcontrollernormal 2x" src="https://user-images.githubusercontent.com/867772/37719923-7c14046a-2d26-11e8-937b-1f19fef03cb6.png">

**Comment by alanzeino** [comment]
This is likely an issue with Apple's snapshot API (which this library uses). I can't tell if you're using CALayer or UIView, but take a look at this code:

```
- (UIImage *)_imageForViewOrLayer:(id)viewOrLayer
{
  if ([viewOrLayer isKindOfClass:[UIView class]]) {
    if (_usesDrawViewHierarchyInRect) {
      return [UIImage fb_imageForView:viewOrLayer];
    } else {
      return [UIImage fb_imageForViewLayer:viewOrLayer];
    }
  } else if ([viewOrLayer isKindOfClass:[CALayer class]]) {
    return [UIImage fb_imageForLayer:viewOrLayer];
  } else {
    [NSException raise:@"Only UIView and CALayer classes can be snapshotted" format:@"%@", viewOrLayer];
  }
  return nil;
}
```

Figure out what path you're taking, figure out which method in `UIImage+Snapshot` the code is using, and call that manually in a test (you should see the same results). Then you can file a radar knowing the specific API that doesn't support `maskedCorners`.

**Comment by m-ruhl** [comment]
Ok, thanks 👍

**Comment by Foxyboo** [comment]
- [ ] [****]()
