### ISSUE TITLE
Not able to specify reference image directory for a test target using Swift

### ISSUE THREAD

**Issue by nataliq** [uber/ios-snapshot-test-case#31]
As it is pointed out in the README there are [three ways](https://github.com/uber/ios-snapshot-test-case/blob/master/FBSnapshotTestCase/FBSnapshotTestCase.h#L19-L29) of setting reference image directories. The recommended option (2) works fine for most of the cases. However since it is on a scheme level if you have a scheme executing tests from multiple targets, the `$(SOURCE_ROOT)/$(PROJECT_NAME)Tests/ReferenceImages` approach doesn't seem to work very well. 
An example would be:
- `FBSnapshotTestCaseDemo` workspace has few other projects inside - let say `FrameworkA` and `FrameworkB`
- `FrameworkA` project has a test target that uses `FBSnapshotTestCase`
- `FrameworkA` project has a `FrameworkA` scheme where the `FB_REFERENCE_IMAGE_DIR` environment variable is configured - running tests with that scheme works fine
- `FBSnapshotTestCaseDemo` has a `FBSnapshotTestCaseDemo` scheme that includes the tests from `FrameworkA` and `FrameworkB`: **running the tests fails** because `FB_REFERENCE_IMAGE_DIR` is not specified in `FBSnapshotTestCaseDemo`

I guess in a setup like this one (which is pretty common if you have modular project with multiple frameworks) the reference image directories should be specified per target which sounds like the option (1). I was not able to make that work though and then read in Apple's Interoperability guide that 
`The Swift compiler does not include a preprocessor`. I'm not sure if it is a limitation or I'm missing something in the configuration, I can put together a sample project if needed. Any advices are welcome.

**Comment by babbage** [comment]
It is possible to achieve what you want. It is not necessary to use `$(PROJECT_NAME)` in the path to the image directories. 

For instance, in my two targets, I have simply defined the same Environment Variables of: 
$(SOURCE_ROOT)/AcceptanceTests/ReferenceImages
$(SOURCE_ROOT)/AcceptanceTests/FailureDiffs

When the tests are run in either target, they place generated snapshots in these same directories. When the images are created, for both reference images and test images, they are placed in folders that are prepended with the target name, so there is no problem with collision conflicts.

**Comment by alanzeino** [comment]
@robbertvanginkel do you want to share some notes on how we do reference images per target?

**Comment by alanzeino** [comment]
I did some research into this, and @babbage is spot on. If you use `SOURCE_ROOT`, you can have per target environment variables that have different directories. The only tricky part, is that in Xcode you may have to select that scheme (and add it to begin with) for the framework before you run tests:

<img width="495" alt="screen shot 2018-08-30 at 2 35 34 pm" src="https://user-images.githubusercontent.com/470797/44880680-09716900-ac62-11e8-97e3-1231218992c0.png">

Hope this helped! Please reach out if you need more guidance.
