### ISSUE TITLE
Add `isOSSpecific`? 

### ISSUE THREAD

**Issue by ceeK** [uber/ios-snapshot-test-case#39]
In our team we find one of the limitations of using snapshot test case is the need to load up several simulators to create snapshots and run tests. Currently this means that our test suite only passes on a single simulator, which isn't ideal.

Most of the failures on other devices are due to a couple of a reasons:
1) There are genuine differences in UIKit classes between iOS versions.
2) `isDeviceAgnostic` is set to true, and we haven't created snapshots for other devices due to the time required

We think we need a separation between device specific tests and OS specific tests. 

In our test suite, we don't actually care about the device itself as we simulate different sizes internally, thus we don't need to load up more simulators. However, we do care about different iOS versions as things can easily break. 

For example labels changed to prevent windowed lines from iOS 10 to iOS 11. Therefore our tests break but the implementation is actually fine. Right now this means we either need to change the test or add a new snapshot. Adding a new snapshot means we have to use `isDeviceAgnostic`, which limits the snapshot to that specific device. However limiting it to the device in this case is not important.

One potential suggestion is the introduction of a new property `isOSSpecific`, which appends OS versions onto the snapshot test file name. `isDeviceAgnostic` would be renamed to `isDeviceSpecific` and would append the device onto the snapshot test file name. Both could be used independently of each other, or together. I don't think this is a massive change, but it does add flexibility when using snapshots.

I'm happy to do the work on this if this is an acceptable (albeit breaking) change. Otherwise I may fork the repo for our internal use. I thought I'd run the idea past people beforehand.

**Comment by ceeK** [comment]
Just noticed this has already been implemented, we're just quite far behind and using the FB version of the repo.

**Comment by alanzeino** [comment]
Yes this is implemented using `agnosticOptions`, for anyone else curious.
