### ISSUE TITLE
Crash with isDeviceAgnostic = true

### ISSUE THREAD

**Issue by maxibello** [uber/ios-snapshot-test-case#40]
Hi!
I've been learning snapshot testing from this article: https://medium.com/@joesusnick/snapshot-xcui-testing-6a16c7ccd47b
It works fine, but when I set isDeviceAgnostic = true, I got a crash (below). Can anyone help plz?

file:///%3Cunknown%3E: test failure: SnapshotUITestingUITests.testExample1() failed: failed: caught "FBSnapshotTestCaseNilKeyWindowException", "Snapshot tests must be hosted by an application with a key window. Please ensure your test host sets up a key window at launch (either via storyboards or programmatically) and doesn't do anything to remove it while snapshot tests are running."
(
	0   CoreFoundation                      0x0000000108b4e1e6 __exceptionPreprocess + 294
	1   libobjc.A.dylib                     0x00000001081e3031 objc_exception_throw + 48
	2   CoreFoundation                      0x0000000108bc3975 +[NSException raise:format:] + 197
	3   FBSnapshotTestCase                  0x0000000128a78db5 -[UIApplication(StrictKeyWindow) fb_strictKeyWindow] + 149
	4   FBSnapshotTestCase                  0x0000000128a7608b FBDeviceAgnosticNormalizedFileName + 123
	5   FBSnapshotTestCase                  0x0000000128a77d46 -[FBSnapshotTestController _fileNameForSelector:identifier:fileNameType:] + 502
	6   FBSnapshotTestCase                  0x0000000128a77f8c -[FBSnapshotTestController _referenceFilePathForSelector:identifier:] + 92
	7   FBSnapshotTestCase                  0x0000000128a785f0 -[FBSnapshotTestController _saveReferenceImage:selector:identifier:error:] + 176
	8   FBSnapshotTestCase                  0x0000000128a784f4 -[FBSnapshotTestController _recordSnapshotOfViewOrLayer:selector:identifier:error:] + 164
	9   FBSnapshotTestCase                  0x0000000128a76d40 -[FBSnapshotTestController compareSnapshotOfViewOrLayer:selector:identifier:tolerance:error:] + 176
	10  FBSnapshotTestCase                  0x0000000128a75e68 -[FBSnapshotTestCase _compareSnapshotOfViewOrLayer:referenceImagesDirectory:identifier:tolerance:error:] + 280
	11  FBSnapshotTestCase                  0x0000000128a7587b -[FBSnapshotTestCase compareSnapshotOfView:referenceImagesDirectory:identifier:tolerance:error:] + 187
	12  FBSnapshotTestCase                  0x0000000128a7b561 _T0So18FBSnapshotTestCaseCAAE0A17VerifyViewOrLayer33_579516362983431F0BBC0680A74EF145LLyyXl_SS10identifierSo12NSOrderedSetC8suffixes12CoreGraphics7CGFloatV9tolerances12StaticStringV4fileSu4linetF + 1729
	13  FBSnapshotTestCase                  0x0000000128a7ae6f _T0So18FBSnapshotTestCaseCAAE0A10VerifyViewySo6UIViewC_SS10identifierSo12NSOrderedSetC8suffixes12CoreGraphics7CGFloatV9tolerances12StaticStringV4fileSu4linetF + 271
	14  SnapshotTestingSampleUITests        0x0000000128a66fb4 _T028SnapshotTestingSampleUITests0A8TestCaseC10verifyViewys12StaticStringV4file_Su4linetF + 452
	15  SnapshotTestingSampleUITests        0x0000000128a65c68 _T028SnapshotTestingSampleUITests0a9UITestingD0C12testExample1yyF + 72
	16  SnapshotTestingSampleUITests        0x0000000128a65ea4 _T028SnapshotTestingSampleUITests0a9UITestingD0C12testExample1yyFTo + 36
	17  CoreFoundation                      0x0000000108ad1ccc __invoking___ + 140
	18  CoreFoundation                      0x0000000108ad1b84 -[NSInvocation invoke] + 308
	19  XCTest                              0x0000000107a6a01a __24-[XCTestCase invokeTest]_block_invoke.184 + 74
	20  XCTest                              0x0000000107ac4ae3 +[XCTestCase(Failures) performFailableBlock:shouldInterruptTest:] + 36
	21  XCTest                              0x0000000107ac4a2e -[XCTestCase(Failures) _performTurningExceptionsIntoFailuresInterruptAfterHandling:block:] + 54
	22  XCTest                              0x0000000107a69ce3 __24-[XCTestCase invokeTest]_block_invoke + 847
	23  XCTest                              0x0000000107ac9a7d -[XCUITestContext performInScope:] + 248
	24  XCTest                              0x0000000107a6997f -[XCTestCase invokeTest] + 175
	25  XCTest                              0x0000000107a6b555 __26-[XCTestCase performTest:]_block_invoke_2 + 42
	26  XCTest                              0x0000000107ac4ae3 +[XCTestCase(Failures) performFailableBlock:shouldInterruptTest:] + 36
	27  XCTest                              0x0000000107ac4a2e -[XCTestCase(Failures) _performTurningExceptionsIntoFailuresInterruptAfterHandling:block:] + 54
	28  XCTest                              0x0000000107a6b402 __26-[XCTestCase performTest:]_block_invoke.318 + 90
	29  XCTest                              0x0000000107ad1061 +[XCTContext runInContextForTestCase:block:] + 225
	30  XCTest                              0x0000000107a6aaff -[XCTestCase performTest:] + 673
	31  XCTest                              0x0000000107aad727 -[XCTest runTest] + 57
	32  XCTest                              0x0000000107a66341 __27-[XCTestSuite performTest:]_block_invoke + 365
	33  XCTest                              0x0000000107a65b1d -[XCTestSuite _performProtectedSectionForTest:testSection:] + 55
	34  XCTest                              0x0000000107a65dde -[XCTestSuite performTest:] + 296
	35  XCTest                              0x0000000107aad727 -[XCTest runTest] + 57
	36  XCTest                              0x0000000107a66341 __27-[XCTestSuite performTest:]_block_invoke + 365
	37  XCTest                              0x0000000107a65b1d -[XCTestSuite _performProtectedSectionForTest:testSection:] + 55
	38  XCTest                              0x0000000107a65dde -[XCTestSuite performTest:] + 296
	39  XCTest                              0x0000000107aad727 -[XCTest runTest] + 57
	40  XCTest                              0x0000000107a66341 __27-[XCTestSuite performTest:]_block_invoke + 365
	41  XCTest                              0x0000000107a65b1d -[XCTestSuite _performProtectedSectionForTest:testSection:] + 55
	42  XCTest                              0x0000000107a65dde -[XCTestSuite performTest:] + 296
	43  XCTest                              0x0000000107aad727 -[XCTest runTest] + 57
	44  XCTest                              0x0000000107adafa6 __44-[XCTTestRunSession runTestsAndReturnError:]_block_invoke + 40
	45  XCTest                              0x0000000107a7e389 -[XCTestObservationCenter _observeTestExecutionForBlock:] + 594
	46  XCTest                              0x0000000107adadb1 -[XCTTestRunSession runTestsAndReturnError:] + 369
	47  XCTest                              0x0000000107a4cc71 -[XCTestDriver runTestsAndReturnError:] + 447
	48  XCTest                              0x0000000107acfbb1 _XCTestMain + 960
	49  SnapshotTestingSampleUITests-Runner 0x000000010777649f _XCTRunnerRunTests + 57
	50  CoreFoundation                      0x0000000108af0b0c __CFRUNLOOP_IS_CALLING_OUT_TO_A_BLOCK__ + 12
	51  CoreFoundation                      0x0000000108ad52db __CFRunLoopDoBlocks + 331
	52  CoreFoundation                      0x0000000108ad4a84 __CFRunLoopRun + 1284
	53  CoreFoundation                      0x0000000108ad430b CFRunLoopRunSpecific + 635
	54  GraphicsServices                    0x000000010be75a73 GSEventRunModal + 62
	55  UIKit                               0x0000000108fcb057 UIApplicationMain + 159
	56  SnapshotTestingSampleUITests-Runner 0x00000001077766dc main + 42
	57  libdyld.dylib                       0x000000010d402955 start + 1
	58  ???                                 0x0000000000000005 0x0 + 5
)

**Comment by acecilia** [comment]
This is a known issue: https://github.com/facebookarchive/ios-snapshot-test-case/issues/235
In order to work around it, create image identifiers yourself that include the ios version, device, or any other information that you think is needed

**Comment by alanzeino** [comment]
I'm going to remove this restriction soon:

https://github.com/uber/ios-snapshot-test-case/pull/13

For now, use `agnosticOptions` instead of `isDeviceAgnostic`.

**Comment by maxibello** [comment]
Hi @alanzeino! Can you please provide an example how to set agnosticOptions (in swift)?
