### ISSUE TITLE
32 bit screenshot compared on 64 bit

### ISSUE THREAD

**Issue by davevdveen** [uber/ios-snapshot-test-case#42]
By default FBSnapshotVerifyView runs with FBSnapshotTestCaseDefaultSuffixes. The resulting orderedSet contains both "_32" and " _64" suffixes, in different order depending on the architecture. Is there a specific reason why both suffixes are added? I think you only want "_32" on a 32 bit device and "_64" on 64 bit device.

We run into issues with this when a test case fails. What happens is the following:
We have 32 bits images with different screenSize as the 64 bit images. When running a test it loops over the suffixes and starts with 64 bits comparison. When this succeeds the 32 bit comparison is skipped, because `if comparisonSuccess || recordMode { break}`. But when the test case fails it doesn't break the for loop, but continues with the 32 bits comparison which will always fail in our case because it compares 32 bits screenshot with 64 bit screenshots of different sizes. It will overwrite the images of the 64 bit comparison and we end up with a diff image containing images of different sizes.

So the second question I have is why break the for loop of suffixes on success but not on failure?

We can workaround the above issues by explicitly call FBSnapshotVerifyView  with suffixes option depending on the architecture of the test device, but it looks like it should be fixed in the framework itself.

**Comment by Grubas7** [comment]
Is this your case:
https://github.com/facebookarchive/ios-snapshot-test-case/pull/119#discussion-diff-41718978
?

@alanzeino I seen `3.0.0` tag. Is this a good moment to change this behaviour (and finally get rid of macros :P)?

**Comment by chunkyguy** [comment]
Will this resolve the issue: https://github.com/PicnicSupermarket/ios-snapshot-test-case/commit/4f5730b76b8fbca12947844c60435e4ded5f007f ?

**Comment by mazen-kasser** [comment]
Since we don't have 32 bits images with different screenSize as the 64 bit images. So I pass a unified suffixes for both architecture: 
```
    lazy var suffixes: NSOrderedSet = {
        let suffixes = NSOrderedSet(array: [])
        return FBSnapshotTestCaseIs64Bit() ? suffixes.reversed : suffixes.copy() as! NSOrderedSet
    }()
```

**Comment by reidmain** [comment]
I'm with you on this @chunkyguy. It is not clear to me why both of the suffixes would always be attached.
