### ISSUE TITLE
Not saving failed snapshots

### ISSUE THREAD

**Issue by marcelofabri** [uber/ios-snapshot-test-case#51]
I think #44 broke saving failed snapshots if you don't set anything (https://github.com/uber/ios-snapshot-test-case/pull/44/files#diff-00c0098c680647a84df94272d707271eR42).

Adding `_imageDiffDirectory = NSTemporaryDirectory();` on `-[FBSnapshotTestController initWithTestClass:]` fixes the issue for me, but I'm not sure if it's the "right" fix.

I'm using `4.0.0`.

**Comment by marcelofabri** [comment]
I think this is because I'm calling `compareSnapshotOfLayer` and `imageDiffDirectory` is only set when calling `snapshotVerifyViewOrLayer` on `FBSnapshotTestCase`

**Comment by alanzeino** [comment]
You might be right. I made the failed snapshots follow the same fallback mechanism as we use for the reference images by adding this method:

```
- (NSString *)getImageDiffDirectoryWithDefault:(NSString *)dir
{
  NSString *envImageDiffDirectory = [NSProcessInfo processInfo].environment[@"IMAGE_DIFF_DIR"];
  if (envImageDiffDirectory) {
    return envImageDiffDirectory;
  }
  if (dir && dir.length > 0) {
    return dir;
  }
  return NSTemporaryDirectory();
}```

Is it not hitting the final return? When I tested this I think it did for me.

**Comment by marcelofabri** [comment]
That method is not called at all when I'm running the tests.

 It looks like only `snapshotVerifyViewOrLayer` calls it.`compareSnapshotOfView` and `compareSnapshotOfLayer` don't.

**Comment by alanzeino** [comment]
I'm guessing you closed this because it wasn't an issue? 

All three methods seem to work, `snapshotVerifyViewOrLayer:...`, `compareSnapshotOfView:...` and `compareSnapshotOfLayer:...` call through to `_compareSnapshotOfViewOrLayer:...` which sets the image diff directory correctly.

**Comment by marcelofabri** [comment]
I closed by accident, sorry.

**Comment by marcelofabri** [comment]
OK, so I think the problem is that I'm using [Nimble-Snapshots](https://github.com/ashfurrow/Nimble-Snapshots) and it uses `FBSnapshotTestController` directly. 

I'm not sure if this is officially supported and if it should be fixed here, but I'm going to submit a PR on their repo to always set it.

**Comment by alanzeino** [comment]
Yes that makes sense. I figured you must've been using `FBSnapshotTestController` directly.

**Comment by nteissler** [comment]
For anyone coming later: @marcelofabri followed up and fixed this here: https://github.com/ashfurrow/Nimble-Snapshots/pull/171

We were using a similar method, but not ash furrow's library, so I just manually applied the changes at the above PR for us
