### ISSUE TITLE
Misleading naming `deviceAgnostic` and `agnosticOptions`

### ISSUE THREAD

**Issue by zapko** [uber/ios-snapshot-test-case#52]
Sorry for being picky, but it cost me half a day to track the issue down.

*A-gnostic* means not-knowing, thus if `deviceAgnostic == true` it means that object should **not** know about device and that contradicts with what the property is defining:
https://github.com/uber/ios-snapshot-test-case/blob/de1c714952ca6b7f1a40670135297fd761ba43cf/FBSnapshotTestCase/FBSnapshotTestCase.h#L111-L115

The same applies to `agnosticOptions` if one sets `agnosticOptions = .screenSize` the expected intention is to ignore screen size, not taking it into account:
https://github.com/uber/ios-snapshot-test-case/blob/22bd3ceddfad92775a976473b93b88b829457851/FBSnapshotTestCase/FBSnapshotTestCasePlatform.m#L64-L68

**Comment by alanzeino** [comment]
Gonna fix this now with an unfortunate breaking change
