### ISSUE TITLE
Add Carthage support

### ISSUE THREAD

**Issue by lukaszmargielewski** [uber/ios-snapshot-test-case#53]
Is there a reason for not supporting Carthage? 
This would be nice alternative to use this frameworks for people avoiding CocoaPods for certain reasons.

**Comment by Grubas7** [comment]
@lukaszmargielewski Carthage is supported, just not as a precompiled framework. Please check: https://github.com/facebookarchive/ios-snapshot-test-case/issues/81

**Comment by alanzeino** [comment]
> Is there a reason for not supporting Carthage?

I guess the first reason is because I've never used it. The second is because I only want to support and maintain CocoaPods.

I'll look into it (not promising anything).
