### ISSUE TITLE
Strange rendering for UISwitch

### ISSUE THREAD

**Issue by malaba** [uber/ios-snapshot-test-case#56]
Our reference image for a test with `FBSnapshotVerifyView` is strange. The outer green circle is rendered with small pixels, but the inner white circle seems to be rendered fuzzy...

On every machine at my work the test are passing (apparently they render it this way), but on my machine: I render with both circle in "small pixels". Hence the test fail on my machine since the reference is not the same. I can't update the ref since then all others will fail, including our integration machine!

| Reference | FailedTest |
| ------ | ----- |
|<img width="320" alt="testmainalertsectionwithswitchon 2x" src="https://user-images.githubusercontent.com/1399632/47014305-24cd0080-d14a-11e8-9a31-7118df9c83b8.png">|<img width="320" alt="failed_testmainalertsectionwithswitchon 2x" src="https://user-images.githubusercontent.com/1399632/47014310-2a2a4b00-d14a-11e8-92d9-11ee256ab3e8.png">|

What can it be ?

We tried changing many conf in the iOS simulator (Debug and Window menu), to no avail.

**Comment by alanzeino** [comment]
Yes I've seen this before manifesting itself slightly differently in https://github.com/facebookarchive/ios-snapshot-test-case/issues/206

No idea what causes it. If you figure it out let me know.

**Comment by reidmain** [comment]
I am going to close this issue due to inactivity. @malaba if you have any new information please don't hesitate to reopen this and we'll help if we can. Thank you.
