### ISSUE TITLE
Snapshots for iPhone XS Max not generated

### ISSUE THREAD

**Issue by peacemoon** [uber/ios-snapshot-test-case#57]
Anyone succeeded to generate snapshots for iPhone XS Max. My tests work perfectly on all other iPhone Simulators, only for iPhone XS Max, no snapshots are generated. It is really frustrating.

**Comment by rfodge** [comment]
I was able to generate snapshots for XS Max.

**Comment by peacemoon** [comment]
Ok, I close this issue for now, maybe my setup is not correct.
