### ISSUE TITLE
Code inconsistency

### ISSUE THREAD

**Issue by alanzeino** [uber/ios-snapshot-test-case#58]
- fix reversed nil checks
- Improve FBSnapshotTestCaseDemo to support preprocessor setting of FB_REFERENCE_IMAGE_DIR and IMAGE_DIFF_DIR

**Comment by reidmain** [comment]
@alanzeino do we still need to do this? As far as I can tell if you removed `FB_REFERENCE_IMAGE_DIR` and `IMAGE_DIFF_DIR` from the scheme and define it as a preprocessor setting it will work. Is there something else we want to demonstrate?

**Comment by alanzeino** [comment]
> @alanzeino do we still need to do this? As far as I can tell if you removed `FB_REFERENCE_IMAGE_DIR` and `IMAGE_DIFF_DIR` from the scheme and define it as a preprocessor setting it will work. Is there something else we want to demonstrate?

Yeah that's basically what I wanted to show when I created this issue. To make sure that preprocessor setup can't break, by having a sample project using preprocessor that can built and tested on CI.

**Comment by reidmain** [comment]
Ah OK so we still need to create a test to verify this works.

What about "fix reversed nil checks"?

**Comment by alanzeino** [comment]
Lots of `if (nil == foo)` in the code base and it annoyed me

**Comment by reidmain** [comment]
Understood. We'll keep this issue alive then and try to address it soon.
