### ISSUE TITLE
agnosticOptions - screenSize

### ISSUE THREAD

**Issue by devedup** [uber/ios-snapshot-test-case#59]
Environment:
Xcode 10 on Mojave
Using version 4.0.0

`self.agnosticOptions = [.OS, .screenSize]`

Results in my file naming being: 
testWelcomeScreen_12_1_0x0@3x.png

It's return 0x0 for screen size.

**Comment by alanzeino** [comment]
Does the test target you're using have a Host Application?

**Comment by jwilliams-handy** [comment]
I was running into this issue as well because I was testing a library. I ended up adding a dummy test application and setting that as the host application and that resolved it for me.

**Comment by alanzeino** [comment]
As expected, only Host Applications report meaningful values for screen size, and other things.
