### ISSUE TITLE
Snapshots do not render sublayers

### ISSUE THREAD

**Issue by rami-a** [uber/ios-snapshot-test-case#62]
I'm currently trying to integrate this library and have been having issues snapshotting more complex views that include sublayers. The structure of the view includes 2 sublayers on the view's layer to handle more complex shadows. When using this library the shadows do not render when using `FBSnapshotVerifyView`

I have a workaround that makes use of iOS 10's `UIGraphicsImageRenderer` to render the view into an image and then pass that image into a UIImageView and send it along to `FBSnapshotVerifyView` and this gets the job done. See the attached screenshots as an example.

Would it be possible to have support for `UIGraphicsImageRenderer` in order to render and snapshot views that include sublayers?

Thanks!

**Just using `FBSnapshotVerifyView`:**
<img width="70" alt="testdefaultcard 2x" src="https://user-images.githubusercontent.com/2364772/48861904-bdcae900-ed92-11e8-981b-817cca1195ff.png">

**Using `UIGraphicsImageRenderer`:**
<img width="70" alt="testdefaultcard 2x" src="https://user-images.githubusercontent.com/2364772/48861840-9411c200-ed92-11e8-8de8-5c96dca16787.png">

**Comment by rami-a** [comment]
For the Material Components library, we use the following class to handle shadows for our views:

https://github.com/material-components/material-components-ios/blob/develop/components/ShadowLayer/src/MDCShadowLayer.m

This CALayer subclass is set as the `layerClass` for many components. The one I was testing in the above screenshots was `MDCCard`.

A quick overview is that we add a `topShadow` layer and `bottomShadow` layer as sublayers and these were not being displayed without utilizing `UIGraphicsImageRenderer`.

**Comment by alanzeino** [comment]
Happy to accept a PR for this @rami-a, as long as it's opt–in (assuming this option would be much slower than the existing methods for snapshotting in `UIImage+Snapshot`).

**Comment by reidmain** [comment]
@rami-a are your tests not running in a host application by chance?

**Comment by rami-a** [comment]
@reidmain they are running in a host application.

**Comment by reidmain** [comment]
> @reidmain they are running in a host application.

Drat well there goes that theory that it is the problem I have seen in the past where a view gets rendered out differently when it is inside a host application versus being outside one.

Do you have an easy example I could use to add a test to the existing test suite? It would be good to ensure that we don't break this going forward.

I am up for updating the `fb_imageForView` method to just use `UIGraphicsImageRenderer` inside of creating it's own graphics context but I'd like to do some testing with Uber's codebase to see if it causes any issues first. I'll try to get to that today.

**Comment by rami-a** [comment]
@reidmain I'm no longer working on the library so I've lost some of the context but here is the code where we do this (and as mentioned before, the issue occurs when you use multiple sublayers to render the shadow): 
https://github.com/material-components/material-components-ios/blob/develop/components/private/Snapshot/src/SnapshotTestCase/MDCSnapshotTestCase.m#L47

@romoore is the person responsible for this for the material-components-ios library now and may be able to help answer additional questions. Thanks!

**Comment by reidmain** [comment]
> @reidmain I'm no longer working on the library so I've lost some of the context but here is the code where we do this (and as mentioned before, the issue occurs when you use multiple sublayers to render the shadow):
> https://github.com/material-components/material-components-ios/blob/develop/components/private/Snapshot/src/SnapshotTestCase/MDCSnapshotTestCase.m#L47
> 
> @romoore is the person responsible for this for the material-components-ios library now and may be able to help answer additional questions. Thanks!

Thank you @rami-a. I'll look at the Material Components tests and see if I can port something over to test multiple sublayers. I did change to use `UIGraphicsImageRenderer` for the entire Uber repo and there were no changes so it looks like something we can migrate to.

**Comment by reidmain** [comment]
Unfortunately I have not been able to replicate this issue with any tests on our end. But since it looks like a benign change that is backwards compatible I have put up a PR (https://github.com/uber/ios-snapshot-test-case/pull/95/) that makes this change.
