### ISSUE TITLE
Option to remove test's folder from diff directory on test succeeded

### ISSUE THREAD

**Issue by p-nicolaou** [uber/ios-snapshot-test-case#63]
Is the any way at the moment, to remove the generated diff assets once the test is passing again.

**Comment by alanzeino** [comment]
If you don't set a imageDiffDirectory they're stored in a temp directory, is that what you're looking for?

**Comment by p-nicolaou** [comment]
So, if I don't specify IMAGE_DIFF_DIR, then are stored temporarily? Am I correct?

**Comment by alanzeino** [comment]
Yes, if you don't set `IMAGE_DIFF_DIR` it will fallback to a temp directory. Can you try it and let me know if that's what you are looking for?
