### ISSUE TITLE
Snapshots fail when running multiple tests in parallel

### ISSUE THREAD

**Issue by rfodge** [uber/ios-snapshot-test-case#72]
Using iOSSnapshotTestCase version 6.0.0, XCode 10, iOS 11.4, 12.1.  When I run our test cases on only 1 device, or 1 test case against multiple devices, the tests will pass.  When I run the test cases against multiple devices, the test cases will fail and they fail with difference files that looks all gray until you zoom in and you can see differences are found in images on the pages.  i attached a few examples of what the difference files look like.  

Example:
Running this with only 1 test case enabled - the test always passes.  Once I enable another test case, the snapshot now fails.
`xcodebuild -workspace rl.xcworkspace -scheme rl-ui-tests -destination 'platform=iOS Simulator,name=iPhone XS Max,OS=12.1' -destination 'platform=iOS Simulator,name=iPhone XR,OS=12.1' clean build test -enableCodeCoverage NO -quiet`

Is parallel testing currently supported or any way to fix issues with image failures like this? 
<img width="50" alt="reference_testsnapshotgetdirectionscirclebutton_iphone_xr_ios12 2x" src="https://user-images.githubusercontent.com/11653643/53278306-7ed06a80-36d6-11e9-95c4-d99cd173795d.png">
<img width="50" alt="failed_testsnapshotgetdirectionscirclebutton_iphone_xr_ios12 2x" src="https://user-images.githubusercontent.com/11653643/53278315-8a239600-36d6-11e9-856d-2f7f6919db3a.png">
<img width="50" alt="diff_testsnapshotgetdirectionscirclebutton_iphone_xr_ios12 2x" src="https://user-images.githubusercontent.com/11653643/53278319-8d1e8680-36d6-11e9-8ed7-8e34b5e86827.png">
<img width="382" alt="diff_testsnapshotgetdirectionsbutton_iphone_xr_ios12 2x" src="https://user-images.githubusercontent.com/11653643/53278324-90b20d80-36d6-11e9-9457-df8193b53e48.png">
<img width="382" alt="reference_testsnapshotgetdirectionsbutton_iphone_xr_ios12 2x" src="https://user-images.githubusercontent.com/11653643/53278328-93acfe00-36d6-11e9-9a26-83fc3ed417de.png">
<img width="382" alt="failed_testsnapshotgetdirectionsbutton_iphone_xr_ios12 2x" src="https://user-images.githubusercontent.com/11653643/53278331-96a7ee80-36d6-11e9-8c1b-90cc9b85a136.png">

**Comment by alanzeino** [comment]
Use the recently added `pixelTolerance` feature.
