### ISSUE TITLE
Not including screen scale in file name options can lead to test failures

### ISSUE THREAD

**Issue by NickEntin** [uber/ios-snapshot-test-case#81]
Setting the `fileNameOptions` to not include the screen scale causes newly-recorded snapshots to fail on devices with a scale factor greater than 1, assuming the scale isn't added to the file name another way (e.g. via the identifier).

Steps to reproduce:
1. Set `fileNameOptions` to `.OS`.
2. Run `testView` with `recordMode = true` on iPhone 8 running iOS 11.2. This outputs a file named `testView_11_2.png`.
3. Run `testView` with `recordMode = false` on the same simulator. The test fails with the following error message:
```
failed - Snapshot comparison failed: Optional(Error Domain=FBSnapshotTestControllerErrorDomain Code=3 "Images different sizes" UserInfo={NSLocalizedFailureReason=referenceImage:{200, 100}, image:{100, 50}, FBDiffedImageKey=<UIImage: 0x6000002a79e0> size {200, 100} orientation 0 scale 2.000000, FBReferenceImageKey=<UIImage: 0x6040002a3900> size {200, 100} orientation 0 scale 1.000000, FBCapturedImageKey=<UIImage: 0x6040002a4bc0> size {100, 50} orientation 0 scale 2.000000, NSLocalizedDescription=Images different sizes})
```

The image sizes are different because the generated image has the same size in pixels, but the reference image is read at a scale factor of 1 by default (without a scale specified in the file name) whereas the generated image has the scale factor of the device, so the point dimensions don't match.

There's another tricky part of this, in that it's easy to miss adding the `.screenScale` option when migrating from an older version of the framework that used `agnosticOptions`. When it finds the reference image to use for the image comparison, `UIImage(contentsOfFile:)` will resolve to a file path with `@2x`/`@3x` in the name if a file with the base name doesn't exist. This causes tests with existing reference snapshots to pass, since it resolves the files correctly.

**Comment by NickEntin** [comment]
I think the most straightforward fix for this would be to load the reference image file directly and fail if a file with the _exact_ name is not found.  Alternatively, it could use the scale factor of the current device if one is not specified in the image name, although this could still lead to confusing test failures.

**Comment by reidmain** [comment]
Thanks for reporting this @NickEntin and I apologize for the problems you've experienced.

I agree with your proposed quick fix solution of failing a test if the exact filename does not exist. It isn't ideal but we've never had to deal with this until the `FBSnapshotTestCaseFileNameIncludeOptionScreenScale` option was added.

The bigger issue seems to be omitting `FBSnapshotTestCaseFileNameIncludeOptionScreenScale` as an option never actually seemed to work. If you omit the screen scale option we then have absolutely no information as to what scale an image was saved to disk at so we'd have to make one of two possible assumptions:

1) The developer knows what they are doing and is running the tests with a simulator of the correct scale so just load the image from disk at the scale of the simulator.
2) The developer can't be trusted so save the image to disk at scale 1 and always read it from the disk at scale 1.

I am not a fan of either of these solutions. It seems really important that the scale of the image is embedded in the filename.

We could maybe remove `FBSnapshotTestCaseFileNameIncludeOptionScreenScale` as it has never worked and its implementation is not actually certain.

**Comment by reidmain** [comment]
Good news @NickEntin. Someone found a third solution to this problem and it is backwards compatible https://github.com/uber/ios-snapshot-test-case/pull/100. Turns out we were using the logical sizes of the images to check if they were equal which automatically takes scale into account. If we switch to raw pixels and the image are the same then we can move forward with a comparison because even though the images aren't named "correctly" they are still equal in terms of raw pixels.
