### ISSUE TITLE
Jonathan Dann link points to 404

### ISSUE THREAD

**Issue by beefon** [uber/ios-snapshot-test-case#9]
Such page does not exist, the Facebook says

**Comment by freak4pc** [comment]
The links works fine here. It just leads to his personal Facebook page... nothing that interesting :)

**Comment by alanzeino** [comment]
I can see the page, but I'm friends with him on Facebook. I'll leave it up to them if they want to update those links, but I've left them there since they worked on this a long time ago.

@jonathandann @toddkrabach

**Comment by toddkrabach** [comment]
you can change the links to the github.com account pages if you'd prefer.  it appears that jonathan has hidden his public profile, so it now shows as a 404 if you are not friends with him.
