### ISSUE TITLE
Not support Swift Package Manager (SPM)

### ISSUE THREAD

**Issue by PH9** [uber/ios-snapshot-test-case#91]
Add Package to iOS:

# Package Resolution Failed
"ios-snapshot-test-case" could not be resolved:

`https://github.com/uber/ios-snapshot-test-case has no Package.swift manifest for version 6.0.3`

![Screen Shot 2019-06-27 at 17 41 21](https://user-images.githubusercontent.com/6365973/60260166-14893a00-9903-11e9-9283-ed4fbb666a05.png)

**Comment by reidmain** [comment]
Unfortunately the Swift Package Manager seems to require a very explicit folder structure in order to properly locate your source code as well as your tests. Our project structure is a bit complex because of how we structure our tests so it wouldn't be something we could easily change at the moment.

We are looking into cleaning up our project structure and at that time we will definitely re-evaluate and see if we change things so that the Swift Package Manager can be supported.

**Comment by gabrielPeart** [comment]
> Unfortunately the Swift Package Manager seems to require a very explicit folder structure in order to properly locate your source code as well as your tests. Our project structure is a bit complex because of how we structure our tests so it wouldn't be something we could easily change at the moment.
> 
> We are looking into cleaning up our project structure and at that time we will definitely re-evaluate and see if we change things so that the Swift Package Manager can be supported.

You can specify your folder structure on the `path`, is not necessary to utilise the default `Sources` folder

**Comment by reidmain** [comment]
> You can specify your folder structure on the `path`, is not necessary to utilise the default `Sources` folder

Could you point to some documentation for this? I have not been able to find any examples that break from the Sources/Name convention and there does not appear to be anything on https://swift.org/package-manager

**Comment by gabrielPeart** [comment]
> > You can specify your folder structure on the `path`, is not necessary to utilise the default `Sources` folder
> 
> Could you point to some documentation for this? I have not been able to find any examples that break from the Sources/Name convention and there does not appear to be anything on https://swift.org/package-manager

You can check: https://docs.swift.org/package-manager/PackageDescription/PackageDescription.html#target

```swift
final public class Target {

    /// The different types of a target.
    public enum TargetType : String, Encodable {

        case regular

        case test

        case system
    }

    /// The different types of a target's dependency on another entity.
    public enum Dependency {

        case _targetItem(name: String)

        case _productItem(name: String, package: String?)

        case _byNameItem(name: String)
    }

    /// The name of the target.
    public var name: String

    /// The path of the target, relative to the package root.
    ///
    /// If the path is `nil`, the Swift Package Manager looks for a targets source files at predefined search paths
    /// and in a subdirectory with the target's name.
    ///
    /// The predefined search paths are the following directories under the package root:
    ///   - For regular targets: `Sources`, `Source`, `src`, and `srcs`
    ///   - For test targets: `Tests`, `Sources`, `Source`, `src`, `srcs`
    ///
    /// For example, the Swift Package Manager will look for source files inside the `[PackageRoot]/Sources/[TargetName]` directory.
    ///
    /// Do not escape the package root; that is, values like `../Foo` or `/Foo` are invalid.
    public var path: String?```

**Comment by kemalenver** [comment]
+1 for this please guys.  2/10 of my dependencies don't support the manager.  Would be great to knock you off the list :)

**Comment by bfernandesbfs** [comment]
SPM PR #126

**Comment by p-nicolaou** [comment]
For our project, this is the last dependancy prior moving to SPM. @alanzeino any plans to progress with PR #126 ?

**Comment by cp-satish-v** [comment]
https://github.com/RxSwiftCommunity/RxBinding has no Package.swift manifest for version 0.3.1

**Comment by alanzeino** [comment]
now supported
