### ISSUE TITLE
FBSnapshotVerifyView doesn't seem to work well with SwiftUI

### ISSUE THREAD

**Issue by Czajnikowski** [uber/ios-snapshot-test-case#97]
The issue happens in Xcode 11 beta 2 (11M337n) and beta 3 (11M362v). I know it's an early moment and maybe it's a bug in the SDK, but currently when I invoke this with `recordMode = true` I get a blank snapshot:
```
let viewController = UIHostingController(
    rootView: Text("yo")
)
viewController.view?.frame = CGRect(
    origin: CGPoint.zero,
    size: CGSize(width: 300, height: 500)
)
        
FBSnapshotVerifyView(viewController.view!)
```

**Comment by leohidalgo** [comment]
This has nothing to do with the library, if you check `viewController.view` this is empty (white), that happens to me too

**Comment by leohidalgo** [comment]
In this way, the image is well generated.

`
    let window = UIWindow(frame: CGRect(x: 0, y: 0, width: 100, height: 100))
    let vc = UIHostingController(rootView: ContentView())
    window.rootViewController = vc
    window.makeKeyAndVisible()

    sut = vc.view

    FBSnapshotVerifyView(sut)
`

**Comment by Czajnikowski** [comment]
Yes, works well! Thanks for your help @leohidalgo 🍻😊

**Comment by leohidalgo** [comment]
I would like to discuss why this should be done now and not before. The both option run, why?, I don't know 😬

**Comment by Czajnikowski** [comment]
I checked briefly transcriptions from WWDC vids (searching for „window”), but didn’t find any clue 🤷🏼‍♂️

**Comment by leohidalgo** [comment]
I think I have the answer, 

https://developer.apple.com/documentation/swiftui/color
<img width="760" alt="image" src="https://user-images.githubusercontent.com/207553/61751347-04377400-ad76-11e9-86ae-4546e608e855.png">

The view is only resolved to concrete when it is displayed, In our case in a UIWindow.
